import type { Receipt, User, Budget, LhdnTag, Notification } from '../types';

// Current user data (mock data for development - will be replaced by auth user)
export const currentUser: User = {
    id: 'mock-user-id',
    name: 'Faris',
    email: 'faris@example.com',
    emailVerified: true,
    photoURL: 'https://i.pravatar.cc/150?img=33',
    createdAt: '2024-01-01T00:00:00+08:00',
    timezone: 'Asia/Kuala_Lumpur',
    currency: 'RM',
    lifestyleCap: 2500,
    lifestyleYtd: 2350,
    enableSpouseOverflow: false,
    tier: 'FREE',
    scanCount: 7, // Simulating 7/10 used
    scansRemaining: 3,
    nextResetDate: '2026-02-01T00:00:00+08:00', // Mock next reset
};

// Malaysian merchant names
export const merchants = [
    'Watsons',
    "Lotus's",
    'ZUS Coffee',
    'Inside Scoop',
    'Popular Bookstore',
    'Decathlon',
    'MR DIY',
    'AEON',
    'Guardian',
    'KK Mart',
    'Tealive',
    'Starbucks',
    'MyNews.com',
    'Padini',
    'Uniqlo',
    'Jaya Grocer',
    'Petronas',
    'Shell',
    'TNB',
    'Air Selangor',
    'Grab',
];

// Helper to add required fields to mock receipts
const addAuditFields = (receipt: Partial<Receipt>): Receipt => ({
    ...receipt,
    userId: 'mock-user-id',
    uploadTimestamp: receipt.date || new Date().toISOString(),
    currency: 'RM',
    verificationStatus: 'verified',
} as Receipt);

// Sample receipts with realistic Malaysian context
export const sampleReceipts: Receipt[] = [
    // ==========================================
    // JANUARY 2026 (Current Month)
    // ==========================================
    addAuditFields({
        id: 'jan-1',
        merchant: 'Jaya Grocer',
        merchantCategory: 'Grocery Store',
        location: 'Eco Ardence, Setia Alam',
        receiptNumber: 'JG-2601-089',
        date: '2026-01-17T10:30:00+08:00',
        amount: 245.50,
        subtotal: 231.60,
        tax: 13.90,
        spendingCategory: 'Groceries',
        claimable: false,
        tags: [],
        payment: 'Credit Card',
        items: [
            { id: 'j1-1', name: 'Fresh Salmon Fillet', category: 'Fresh', qty: 2, unit: 45.00, claimable: false },
            { id: 'j1-2', name: 'Australian Ribeye Steak', category: 'Meat', qty: 1, unit: 85.00, claimable: false },
            { id: 'j1-3', name: 'Farm Fresh Milk 2L', category: 'Dairy', qty: 2, unit: 14.50, claimable: false },
            { id: 'j1-4', name: 'Organic Spinach', category: 'Vegetable', qty: 3, unit: 8.50, claimable: false },
        ],
        customTags: ['Weekly', 'Family'],
    }),
    addAuditFields({
        id: 'jan-2',
        merchant: 'Warung Pak Mat',
        merchantCategory: 'Restaurant',
        location: 'Shah Alam Sek 7',
        receiptNumber: 'MANUAL',
        date: '2026-01-16T13:00:00+08:00',
        amount: 18.50,
        subtotal: 17.00,
        tax: 0,
        taxRate: 0,
        serviceChargeRate: 0,
        serviceChargeAmount: 0,
        rounding: 1.50,
        spendingCategory: 'Dining & Food',
        claimable: false,
        tags: [],
        payment: 'Cash',
        items: [
            { id: 'j2-1', name: 'Nasi Campur Ayam Goreng', category: 'Food', qty: 1, unit: 12.00, claimable: false },
            { id: 'j2-2', name: 'Teh O Ais Limau', category: 'Beverage', qty: 1, unit: 3.50, claimable: false },
            { id: 'j2-3', name: 'Kuih Muih', category: 'Food', qty: 3, unit: 0.50, claimable: false },
        ],
        customTags: ['Lunch', 'Work'],
    }),
    addAuditFields({
        id: 'jan-3',
        merchant: 'Watsons',
        merchantCategory: 'Beauty & Personal Care',
        location: 'Setia City Mall',
        receiptNumber: 'W-99283',
        date: '2026-01-15T18:45:00+08:00',
        amount: 128.90,
        subtotal: 128.90,
        spendingCategory: 'Healthcare',
        claimable: true,
        tags: ['Medical', 'Lifestyle'],
        payment: 'eWallet',
        items: [
            { id: 'j3-1', name: 'Blackmores Multivitamin', category: 'Supplements', qty: 1, unit: 65.00, claimable: true, tag: 'Medical' },
            { id: 'j3-2', name: 'Nivea Men Deodorant', category: 'Personal Care', qty: 2, unit: 14.50, claimable: true, tag: 'Lifestyle' },
            { id: 'j3-3', name: 'Colgate Optic White', category: 'Personal Care', qty: 1, unit: 34.90, claimable: true, tag: 'Lifestyle' },
        ],
        customTags: ['Health'],
    }),
    addAuditFields({
        id: 'jan-4',
        merchant: 'Shell',
        merchantCategory: 'Others',
        location: 'NKVE Damansara',
        receiptNumber: 'SH-2938',
        date: '2026-01-14T08:15:00+08:00',
        amount: 85.00,
        subtotal: 85.00,
        spendingCategory: 'Transportation',
        claimable: false,
        tags: [],
        payment: 'Credit Card',
        items: [
            { id: 'j4-1', name: 'Ron 95 Fuel', category: 'Fuel', qty: 41.46, unit: 2.05, claimable: false },
        ],
        customTags: ['Car'],
    }),
    addAuditFields({
        id: 'jan-5',
        merchant: 'TNB',
        merchantCategory: 'Others',
        location: 'Online',
        receiptNumber: 'TNB-JAN26',
        date: '2026-01-10T09:00:00+08:00',
        amount: 345.20,
        subtotal: 345.20,
        spendingCategory: 'Utilities',
        claimable: false,
        tags: [],
        payment: 'eWallet',
        items: [
            { id: 'j5-1', name: 'Electricity Bill - Jan 2026', category: 'Utilities', qty: 1, unit: 345.20, claimable: false },
        ],
        customTags: ['Bills', 'House'],
    }),
    addAuditFields({
        id: 'jan-6',
        merchant: 'ZUS Coffee',
        merchantCategory: 'Coffee Shop',
        location: 'Glenmarie',
        receiptNumber: 'ZS-9921',
        date: '2026-01-08T15:30:00+08:00',
        amount: 24.80,
        subtotal: 24.80,
        spendingCategory: 'Dining & Food',
        claimable: false,
        tags: [],
        payment: 'eWallet',
        items: [
            { id: 'j6-1', name: 'Spanish Latte', category: 'Coffee', qty: 2, unit: 12.40, claimable: false },
        ],
        customTags: ['Coffee', 'Treat'],
    }),
    addAuditFields({
        id: 'jan-7',
        merchant: 'Popular Bookstore',
        merchantCategory: 'Bookstore',
        location: 'Paradigm Mall',
        receiptNumber: 'POP-001',
        date: '2026-01-05T19:00:00+08:00',
        amount: 156.00,
        subtotal: 156.00,
        spendingCategory: 'Education',
        claimable: true,
        tags: ['Books'],
        payment: 'eWallet',
        items: [
            { id: 'j7-1', name: 'Business Strategy Book', category: 'Books', qty: 1, unit: 85.00, claimable: true, tag: 'Books' },
            { id: 'j7-2', name: 'Moleskine Notebook', category: 'Stationery', qty: 1, unit: 71.00, claimable: true, tag: 'Books' },
        ],
        customTags: ['Self-dev'],
    }),

    // ==========================================
    // DECEMBER 2025 (Year End / Holiday)
    // ==========================================
    addAuditFields({
        id: 'dec-1',
        merchant: 'Uniqlo',
        merchantCategory: 'Fashion & Apparel',
        location: 'One Utama',
        receiptNumber: 'UQ-8821',
        date: '2025-12-28T14:45:00+08:00',
        amount: 399.60,
        subtotal: 399.60,
        spendingCategory: 'Shopping',
        claimable: false,
        tags: [],
        payment: 'Credit Card',
        items: [
            { id: 'd1-1', name: 'Airism Oversized Tee', category: 'Apparel', qty: 4, unit: 59.90, claimable: false },
            { id: 'd1-2', name: 'Selvedge Jeans', category: 'Apparel', qty: 1, unit: 159.90, claimable: false },
        ],
        customTags: ['Clothes'],
    }),
    addAuditFields({
        id: 'dec-2',
        merchant: 'Decathlon',
        merchantCategory: 'Sports & Fitness',
        location: 'Shah Alam',
        receiptNumber: 'DEC-7721',
        date: '2025-12-24T11:00:00+08:00',
        amount: 450.00,
        subtotal: 450.00,
        spendingCategory: 'Shopping',
        claimable: true,
        tags: ['Sports'],
        payment: 'Credit Card',
        items: [
            { id: 'd2-1', name: 'Running Shoes Kiprun', category: 'Footwear', qty: 1, unit: 250.00, claimable: true, tag: 'Sports' },
            { id: 'd2-2', name: 'Dumbbell Set 20kg', category: 'Equipment', qty: 1, unit: 200.00, claimable: true, tag: 'Sports' },
        ],
        customTags: ['Fitness', 'New Year Res'],
    }),
    addAuditFields({
        id: 'dec-3',
        merchant: 'Mamak Hakim',
        merchantCategory: 'Restaurant',
        location: 'Subang Bestari',
        receiptNumber: 'MANUAL',
        date: '2025-12-20T21:30:00+08:00',
        amount: 30.83,
        subtotal: 28.00,
        tax: 1.68,
        taxRate: 0.06,
        serviceChargeRate: 10,
        serviceChargeAmount: 2.80,
        rounding: -1.65,
        spendingCategory: 'Dining & Food',
        claimable: false,
        tags: [],
        payment: 'eWallet',
        items: [
            { id: 'd3-1', name: 'Roti Canai Telur', category: 'Food', qty: 2, unit: 3.50, claimable: false },
            { id: 'd3-2', name: 'Maggi Goreng Mamak', category: 'Food', qty: 1, unit: 8.50, claimable: false },
            { id: 'd3-3', name: 'Teh Tarik Kurang Manis', category: 'Beverage', qty: 2, unit: 3.00, claimable: false },
            { id: 'd3-4', name: 'Ayam Goreng', category: 'Food', qty: 1, unit: 7.00, claimable: false },
        ],
        customTags: ['Late-night'],
    }),
    addAuditFields({
        id: 'dec-4',
        merchant: "Lotus's",
        merchantCategory: 'Grocery Store',
        location: 'Ara Damansara',
        receiptNumber: 'LTS-8812',
        date: '2025-12-15T16:20:00+08:00',
        amount: 312.45,
        subtotal: 312.45,
        spendingCategory: 'Groceries',
        claimable: false,
        tags: [],
        payment: 'Credit Card',
        items: [
            { id: 'd4-1', name: 'Weekly Groceries', category: 'Groceries', qty: 1, unit: 312.45, claimable: false },
        ],
        customTags: ['Weekly'],
    }),
    addAuditFields({
        id: 'dec-5',
        merchant: 'Air Selangor',
        merchantCategory: 'Others',
        location: 'Online',
        receiptNumber: 'AS-DEC25',
        date: '2025-12-05T10:00:00+08:00',
        amount: 45.60,
        subtotal: 45.60,
        spendingCategory: 'Utilities',
        claimable: false,
        tags: [],
        payment: 'eWallet',
        items: [
            { id: 'd5-1', name: 'Water Bill - Dec 2025', category: 'Utilities', qty: 1, unit: 45.60, claimable: false },
        ],
        customTags: ['Bills'],
    }),

    // ==========================================
    // NOVEMBER 2025
    // ==========================================
    addAuditFields({
        id: 'nov-1',
        merchant: 'Padini Concept Store',
        merchantCategory: 'Fashion & Apparel',
        location: 'Sunway Pyramid',
        receiptNumber: 'PAD-1120',
        date: '2025-11-28T15:15:00+08:00',
        amount: 158.00,
        subtotal: 158.00,
        spendingCategory: 'Shopping',
        claimable: false,
        tags: [],
        payment: 'Card',
        items: [
            { id: 'n1-1', name: 'Work Slacks', category: 'Apparel', qty: 2, unit: 79.00, claimable: false },
        ],
        customTags: ['Work'],
    }),
    addAuditFields({
        id: 'nov-2',
        merchant: '99 Speedmart',
        merchantCategory: 'Convenience Store',
        location: 'Taman Saujana',
        receiptNumber: '99-2831',
        date: '2025-11-20T19:30:00+08:00',
        amount: 42.50,
        subtotal: 42.50,
        spendingCategory: 'Groceries',
        claimable: false,
        tags: [],
        payment: 'Cash',
        items: [
            { id: 'n2-1', name: 'Gardenia Bread', category: 'Bakery', qty: 1, unit: 4.50, claimable: false },
            { id: 'n2-2', name: 'Eggs Grade A (30s)', category: 'Fresh', qty: 1, unit: 13.50, claimable: false },
            { id: 'n2-3', name: 'Milo 1kg', category: 'Groceries', qty: 1, unit: 24.50, claimable: false },
        ],
        customTags: ['Essentials'],
    }),
    addAuditFields({
        id: 'nov-3',
        merchant: 'Grab',
        merchantCategory: 'Others',
        location: 'App',
        receiptNumber: 'GRB-9912',
        date: '2025-11-15T08:45:00+08:00',
        amount: 24.00,
        subtotal: 24.00,
        spendingCategory: 'Transportation',
        claimable: false,
        tags: [],
        payment: 'eWallet',
        items: [
            { id: 'n3-1', name: 'Ride to Office', category: 'Transport', qty: 1, unit: 24.00, claimable: false },
        ],
        customTags: ['Commute'],
    }),
    addAuditFields({
        id: 'nov-4',
        merchant: 'Gerai Nasi Lemak Mak Cik',
        merchantCategory: 'Restaurant',
        location: 'Roadside Stall',
        receiptNumber: 'MANUAL',
        date: '2025-11-10T07:30:00+08:00',
        amount: 6.50,
        subtotal: 6.50,
        spendingCategory: 'Dining & Food',
        claimable: false,
        tags: [],
        payment: 'Cash',
        items: [
            { id: 'n4-1', name: 'Nasi Lemak Biasa', category: 'Food', qty: 1, unit: 3.50, claimable: false },
            { id: 'n4-2', name: 'Ayam Goreng', category: 'Food', qty: 1, unit: 3.00, claimable: false },
        ],
        customTags: ['Breakfast'],
    }),
    addAuditFields({
        id: 'nov-5',
        merchant: 'Guardian',
        merchantCategory: 'Pharmacy & Health',
        location: 'Aeon Shah Alam',
        receiptNumber: 'GRD-5511',
        date: '2025-11-05T13:00:00+08:00',
        amount: 89.90,
        subtotal: 89.90,
        spendingCategory: 'Healthcare',
        claimable: true,
        tags: ['Medical'],
        payment: 'Credit Card',
        items: [
            { id: 'n5-1', name: 'Fish Oil Supplements', category: 'Supplements', qty: 1, unit: 89.90, claimable: true, tag: 'Medical' },
        ],
        customTags: ['Health'],
    }),
];

// Budget data for legacy user (snaplytic.digital@gmail.com)
export const currentBudget: Budget = {
    month: '2026-01',
    total: 3500,
    isSetup: true,
    categories: [
        { id: 'dining-food', name: 'Dining & Food', amount: 900, isPreset: true, icon: '🍽️' },
        { id: 'groceries', name: 'Groceries', amount: 600, isPreset: true, icon: '🛒' },
        { id: 'transportation', name: 'Transportation', amount: 300, isPreset: true, icon: '🚗' },
        { id: 'utilities', name: 'Utilities', amount: 400, isPreset: true, icon: '💡' },
        { id: 'shopping', name: 'Shopping', amount: 400, isPreset: true, icon: '🛍️' },
        { id: 'healthcare', name: 'Healthcare', amount: 200, isPreset: true, icon: '💊' },
        { id: 'entertainment', name: 'Entertainment', amount: 300, isPreset: true, icon: '🎬' },
        { id: 'education', name: 'Education', amount: 200, isPreset: true, icon: '📚' },
        { id: 'others', name: 'Others', amount: 200, isPreset: true, icon: '📦' },
    ],
};

// Empty budget for new users
export const emptyBudget: Budget = {
    month: new Date().toISOString().slice(0, 7),
    total: 0,
    isSetup: false,
    categories: [
        { id: 'dining-food', name: 'Dining & Food', amount: 0, isPreset: true, icon: '🍽️' },
        { id: 'groceries', name: 'Groceries', amount: 0, isPreset: true, icon: '🛒' },
        { id: 'transportation', name: 'Transportation', amount: 0, isPreset: true, icon: '🚗' },
        { id: 'utilities', name: 'Utilities', amount: 0, isPreset: true, icon: '💡' },
        { id: 'shopping', name: 'Shopping', amount: 0, isPreset: true, icon: '🛍️' },
        { id: 'healthcare', name: 'Healthcare', amount: 0, isPreset: true, icon: '💊' },
        { id: 'entertainment', name: 'Entertainment', amount: 0, isPreset: true, icon: '🎬' },
        { id: 'education', name: 'Education', amount: 0, isPreset: true, icon: '📚' },
        { id: 'others', name: 'Others', amount: 0, isPreset: true, icon: '📦' },
    ],
};

// Sample notifications
export const sampleNotifications: Notification[] = [
    {
        id: '1',
        message: 'Lifestyle tax relief cap at 94% (RM 2,350 of RM 2,500)',
        timestamp: '2026-01-15T14:30:00+08:00',
        read: false,
        type: 'warning',
    },
    {
        id: '2',
        message: 'Decathlon Sport Sale ends this weekend!',
        timestamp: '2026-01-12T09:00:00+08:00',
        read: false,
        type: 'info',
    },
    {
        id: '3',
        message: 'December 2025 Spending Report Ready',
        timestamp: '2026-01-01T08:00:00+08:00',
        read: true,
        type: 'success',
    },
];

// LHDN tag metadata
export const lhdnTagColors: Record<LhdnTag, string> = {
    'Lifestyle': 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200',
    'Education': 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200',
    'Medical': 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200',
    'Childcare': 'bg-pink-100 text-pink-800 dark:bg-pink-900 dark:text-pink-200',
    'Books': 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200',
    'Sports': 'bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200',
    'Others': 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200',
};
