// Core type definitions for MyReceipt app

export type LhdnTag =
    | 'Lifestyle'
    | 'Education'
    | 'Medical'
    | 'Childcare'
    | 'Books'
    | 'Sports'
    | 'Others';

export type SpendingCategory =
    | 'Groceries'
    | 'Dining & Food'
    | 'Transportation'
    | 'Healthcare'
    | 'Entertainment'
    | 'Shopping'
    | 'Education'
    | 'Utilities'
    | 'Others';

export type MerchantCategory =
    | 'Restaurant'
    | 'Coffee Shop'
    | 'Bakery & Desserts'
    | 'Grocery Store'
    | 'Convenience Store'
    | 'Electronics'
    | 'Mobile & Gadgets'
    | 'Computer & IT'
    | 'Gaming'
    | 'Sports & Fitness'
    | 'Fashion & Apparel'
    | 'Beauty & Personal Care'
    | 'Pharmacy & Health'
    | 'Bookstore'
    | 'Department Store'
    | 'Hardware & DIY'
    | 'Others';

export type PaymentMethod = 'Cash' | 'Card' | 'eWallet' | 'Credit Card';

export type VerificationStatus = 'pending' | 'verified' | 'rejected';

export interface LineItem {
    id: string;
    receiptId?: string;                // FK to receipt (for Firestore)
    name: string;
    category?: string;
    qty: number;
    unit: number;
    claimable: boolean;
    tag?: LhdnTag;
    productTags?: string[]; // NLP tags
    autoAssigned?: boolean; // True if LHDN tag was auto-generated by AI
}

export interface Receipt {
    id: string;
    userId: string;                    // FK to user (required)
    merchant: string;
    merchantCategory: MerchantCategory;
    location?: string;
    receiptNumber?: string;
    date: string;                      // Receipt date (ISO)
    uploadTimestamp: string;           // When uploaded to system (ISO)
    amount: number;
    subtotal?: number;
    tax?: number;
    taxRate?: number;                  // Primary tax (SST %)
    serviceChargeRate?: number;        // Service Charge % (0, 6, 8, 10)
    serviceChargeAmount?: number;      // Calculated service charge
    rounding?: number;                 // Bill rounding adjustment
    currency: string;                  // e.g., 'RM'
    spendingCategory: SpendingCategory;
    claimable: boolean;
    tags: LhdnTag[];
    customTags?: string[];
    items: LineItem[];
    payment: PaymentMethod;
    notes?: string;
    routedToSpouse?: boolean;
    receiptImageUrl?: string;          // Cloud storage URL
    rawOcrText?: string;               // Original OCR output (immutable)
    verificationStatus: VerificationStatus;
    // XP tracking for anti-farming (Phase 3)
    pointsAwarded?: {
        upload?: boolean;      // +10 XP awarded
        verified?: boolean;    // +5 XP for verifying details  
        categorized?: boolean; // +5 XP for confirming category
    };
}

export interface Transaction {
    id: string;
    userId: string;                    // FK to user
    receiptIds: string[];              // FKs to receipts
    totalAmount: number;
    category: string;
    transactionDate: string;           // ISO date
    createdAt: string;                 // ISO timestamp
}

export interface BudgetCategory {
    id: string;
    name: string;
    amount: number;
    isPreset: boolean;  // true for Bills, Food & Beverages, Fuel
    icon?: string;
}

export interface Budget {
    id?: string;
    userId?: string;
    month: string;
    total: number;
    categories: BudgetCategory[];
    isSetup: boolean;  // false for new users who haven't set up budget
}

// Preset budget categories for MVP
export const PRESET_BUDGET_CATEGORIES: Omit<BudgetCategory, 'amount'>[] = [
    { id: 'bills', name: 'Bills', isPreset: true, icon: '📄' },
    { id: 'food-beverage', name: 'Food & Beverages', isPreset: true, icon: '🍽️' },
    { id: 'fuel', name: 'Fuel', isPreset: true, icon: '⛽' },
];

// Maximum custom categories user can add
export const MAX_CUSTOM_CATEGORIES = 7;

export interface SpouseInfo {
    name: string;
    email: string;
}

export interface User {
    id: string;                        // Firebase UID (unique)
    email: string;
    name: string;
    emailVerified: boolean;
    photoURL?: string;
    createdAt: string;                 // Account creation timestamp
    timezone: string;                  // e.g., 'Asia/Kuala_Lumpur'
    currency: string;                  // e.g., 'RM'
    spouse?: SpouseInfo;
    lifestyleCap: number;
    lifestyleYtd: number;
    enableSpouseOverflow?: boolean;
    // Freemium Tier Fields
    tier: 'FREE' | 'PRO';
    scanCount: number; // Monthly usage (for stats)
    scansRemaining: number; // The wallet (starts at 10, +3 for ads)
    nextResetDate: string; // ISO timestamp for next reset (Anniversary Billing)
    lastAdWatch?: string; // ISO timestamp
    proExpiryDate?: string; // ISO timestamp
}

export interface CategorySummary {
    category: string;
    amount: number;
    percent: number;
    icon?: string;
}

export interface AnalyticsData {
    totalSpend: number;
    claimableTotal: number;
    nonClaimableTotal: number;
    categoryBreakdown: CategorySummary[];
    dailySpend: { date: string; amount: number }[];
}

export interface Notification {
    id: string;
    userId?: string;
    message: string;
    timestamp: string;
    read: boolean;
    type: 'info' | 'warning' | 'success';
}
